services:
  django:
    build: .
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - django_settings
    environment:
      ENV_PATH: /run/secrets/django_settings
    command: >
      bash -c "hatch run ./manage.py migrate &&
               hatch run gunicorn --bind 0.0.0.0:3000 eli.wsgi:application"
    ports:
      - "3000"
    volumes:
      - ./src:/code/src
        

  nginx:
    build: ./nginx
    ports:
      - 8000:3001
    depends_on:
      - django

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresl/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 100
      start_period: 1s
      timeout: 10s

secrets:
  django_settings:
    file: .env


volumes:
  db_data:
