services:
  django:
    build: .
    secrets:
      - django_settings
    environment:
      ENV_PATH: /run/secrets/django_settings
    command: >
      bash -c "hatch run ./manage.py migrate &&
               hatch run gunicorn --bind 0.0.0.0:3000 eli.wsgi:application"
    ports:
      - "3000"
    
  web_migrate:
    extends:
      service: django
    command: hatch run ./manage.py migrate
    profiles: [disabled]
        

  nginx:
    build: ./nginx
    ports:
      - 8000:3001
    depends_on:
      - django

secrets:
  django_settings:
    file: .env
