services:
  django:
    build: .
    secrets:
      - django_settings
    environment:
      ENV_PATH: /run/secrets/django_settings
    command: >
      bash -c "(until pg_isready --host db --timeout 30; do sleep 1; done) &&
               hatch run ./manage.py migrate &&
               hatch run gunicorn --bind 0.0.0.0:3000 eli.wsgi:application"
    ports:
      - "3000"
        

  nginx:
    build: ./nginx
    ports:
      - 8000:3001
    depends_on:
      - django

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresl/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

secrets:
  django_settings:
    file: .env


volumes:
  db_data:
