services:
  django_base:
    build: .
    secrets:
      - django_settings
    environment:
      ENV_PATH: /run/secrets/django_settings
    env_file:
      - .env
    volumes:
      - ./src:/code/src
      - static:/static
      - js-out:/js-out
    user: "${UID}:${GID}"
    command: "bash -c exit"

  migrate:
    extends: django_base
    command: "hatch run ./migrate.sh"
    
  collectstatic:
    extends: django_base
    depends_on:
      migrate:
        condition: service_completed_successfully
      build-frontend:
        condition: service_completed_successfully
    command: "hatch run ./manage.py collectstatic --clear --no-input"

  django:
    extends: django_base
    depends_on:
      collectstatic:
        condition: service_completed_successfully
    command: "hatch run ./entrypoint.sh"

  build-frontend:
    build : ./src/frontend
    volumes:
      - ./src/frontend/:/js/src/
      - js-out:/js/out/
    command: "npm run build"
    
  nginx:
    build: ./nginx
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - django
    volumes:
      - static:/static
      - ./ssl:/ssl

  db:
    image: postgres:15
    volumes:
      - ./db_data:/var/lib/postgresql/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

secrets:
  django_settings:
    file: .env


volumes:
  static:
  js-out:
