# Generated by Django 5.1 on 2024-09-29 02:46

from django.db import migrations, models

import eli_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("eli_app", "0008_rename_raw_response_conversation_response_raw_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatResponseEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eli_app.models.random_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ImageResponseEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=eli_app.models.random_id,
                        editable=False,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
