# Generated by Django 5.1 on 2024-10-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eli_app", "0010_delete_imageresponseevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="eli_app.conversation",
                    ),
                ),
                ("start_timestamp", models.DateTimeField(auto_now_add=True)),
                ("revised_prompt", models.TextField(blank=True)),
                ("data", models.BinaryField(blank=True)),
            ],
        ),
    ]
